---
exclude: ['README.markdown']
permalink: ':title'
pygments: true
safe: true
title: 'PPM_Synth Class Reference'

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge